# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# pre-commit install        啟用指定的 git hook
# pre-commit autoupdate     更新以下 repo 的版本
# pre-commit run --all-files 全檔案檢查，而不是只有被提交的檔案
# pre-commit run --hook-stage manual --all-files  如果需要額外檢查 manual 的項目
# pre-commit run <hook_id> --all-files 只檢查特定一個 hook 是否通過

# SKIP=check-added-large-files git commit -m "提交訊息"    暫時跳過特定 hock
# git commit --no-verify 或者 git commit -n               跳過所有 commit hock
# git push --no-verify                                   跳過所有 push hock

default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.6.1
    hooks:
      - id: conventional-gitmoji
        stages: [commit-msg]
