name: vad
description: "VAD is a cross-platform Dart binding for the VAD JavaScript library.
  This package provides access to a Voice Activity Detection (VAD) system, allowing Flutter applications to start and stop VAD-based listening and handle various VAD events."
version: 0.0.2
repository: https://github.com/keyur2maru/vad

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - vad
  - voice-activity-detection
  - vad-flutter
  - vad-dart
  - silero-vad